# Generated by Django 4.2.1 on 2023-09-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_participant_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
